version: "3"
services:
  mongo:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password 
    volumes:
      - mongodata:/data/db
  growthbook:
    image: "growthbook/growthbook:latest"
    ports:
      - "4000:3000"
      - "4100:3100"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://aptible:xn9P4wM9yCH3BDkuM857whULVJP9RW8y@db-fortuna-non-prod-144255.aptible.in:20855/db?ssl=true
      - APP_ORIGIN=https://growthbook-fortuna-app-stg-green.on-aptible.com
      - API_HOST=https://growthbook-fortuna-app-stg-green.on-aptible.com
    volumes:
      - uploads:/usr/local/src/app/packages/back-end/uploads
volumes:
  uploads:
  mongodata:
